/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo */
        post: operations["demo_auth_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Profile */
        put: operations["save_profile_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Garments */
        get: operations["list_garments_garments_get"];
        put?: never;
        /** Create Garment */
        post: operations["create_garment_garments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Garment */
        put: operations["edit_garment_garments__id__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_garments__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/garments/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Archive */
        patch: operations["archive_garments__id__archive_patch"];
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image */
        get: operations["image_images__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outfits/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_outfits_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outfits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outfit */
        get: operations["get_outfit_outfits__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outfits/{id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjustment */
        post: operations["adjustment_outfits__id__adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outfits/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_outfits__id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentInput */
        AdjustmentInput: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "warmer" | "cooler" | "casual" | "formal";
        };
        /** AdjustmentView */
        AdjustmentView: {
            outfit: components["schemas"]["OutfitView"];
            /** Original Id */
            original_id: string;
            /** Replacement Id */
            replacement_id: string;
            /** Direction */
            direction: string;
            /** Explanation */
            explanation: string;
        };
        /** AnalysisView */
        AnalysisView: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            proposed: components["schemas"]["Attributes"];
            /** Uncertainty */
            uncertainty: string | null;
            /** Warning */
            warning: string | null;
            /** Image Url */
            image_url: string;
        };
        /** ArchiveInput */
        ArchiveInput: {
            /** Archived */
            archived: boolean;
        };
        /** Attributes */
        Attributes: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "shirt" | "knit" | "trousers" | "skirt" | "jeans" | "dress" | "jumpsuit" | "sneakers" | "loafers" | "dress_shoes" | "boots" | "coat" | "jacket" | "scarf" | "bag";
            /**
             * Slot
             * @enum {string}
             */
            slot: "top" | "bottom" | "shoes" | "onepiece" | "outerwear" | "accessory";
            /**
             * Audience
             * @default unisex
             * @enum {string}
             */
            audience: "men" | "women" | "unisex";
            /**
             * Primary Color
             * @enum {string}
             */
            primary_color: "black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow";
            /** Secondary Color */
            secondary_color?: ("black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow") | null;
            /**
             * Pattern
             * @default solid
             * @enum {string}
             */
            pattern: "solid" | "striped" | "checked" | "floral" | "graphic";
            /** Warmth */
            warmth: number;
            /** Formality */
            formality: number;
            /** Seasons */
            seasons?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Weather */
            weather?: ("dry" | "rain" | "wind")[];
            /** Tags */
            tags?: string[];
            /**
             * Laundry
             * @default clean
             * @enum {string}
             */
            laundry: "clean" | "dirty" | "unavailable";
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_upload_uploads_post */
        Body_upload_uploads_post: {
            /** File */
            file: string;
        };
        /** Context */
        Context: {
            /**
             * Occasion
             * @default job interview
             */
            occasion: string;
            /**
             * Temperature
             * @default 12
             */
            temperature: number;
            /**
             * Precipitation
             * @default dry
             * @enum {string}
             */
            precipitation: "dry" | "rain";
            /**
             * Wind
             * @default 8
             */
            wind: number;
            /**
             * Min Formality
             * @default 2
             */
            min_formality: number;
            /**
             * Max Formality
             * @default 4
             */
            max_formality: number;
            /** Required */
            required?: string[];
            /** Excluded */
            excluded?: string[];
            /**
             * Outerwear
             * @default true
             */
            outerwear: boolean;
            /**
             * Accessory
             * @default false
             */
            accessory: boolean;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** FeedbackInput */
        FeedbackInput: {
            /**
             * Event
             * @enum {string}
             */
            event: "wore" | "liked" | "disliked" | "skipped";
            /** Reason */
            reason?: ("too formal" | "too casual" | "too cold" | "too warm" | "don’t like the colors") | null;
        };
        /** FeedbackView */
        FeedbackView: {
            /** Id */
            id: string;
            /** Outfit Id */
            outfit_id: string;
            /** Event */
            event: string;
            /** Reason */
            reason: string | null;
            /** Created At */
            created_at: string;
        };
        /** GarmentInput */
        GarmentInput: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "shirt" | "knit" | "trousers" | "skirt" | "jeans" | "dress" | "jumpsuit" | "sneakers" | "loafers" | "dress_shoes" | "boots" | "coat" | "jacket" | "scarf" | "bag";
            /**
             * Slot
             * @enum {string}
             */
            slot: "top" | "bottom" | "shoes" | "onepiece" | "outerwear" | "accessory";
            /**
             * Audience
             * @default unisex
             * @enum {string}
             */
            audience: "men" | "women" | "unisex";
            /**
             * Primary Color
             * @enum {string}
             */
            primary_color: "black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow";
            /** Secondary Color */
            secondary_color?: ("black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow") | null;
            /**
             * Pattern
             * @default solid
             * @enum {string}
             */
            pattern: "solid" | "striped" | "checked" | "floral" | "graphic";
            /** Warmth */
            warmth: number;
            /** Formality */
            formality: number;
            /** Seasons */
            seasons?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Weather */
            weather?: ("dry" | "rain" | "wind")[];
            /** Tags */
            tags?: string[];
            /**
             * Laundry
             * @default clean
             * @enum {string}
             */
            laundry: "clean" | "dirty" | "unavailable";
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Suggestion Id */
            suggestion_id?: string | null;
        };
        /** GarmentView */
        GarmentView: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "shirt" | "knit" | "trousers" | "skirt" | "jeans" | "dress" | "jumpsuit" | "sneakers" | "loafers" | "dress_shoes" | "boots" | "coat" | "jacket" | "scarf" | "bag";
            /**
             * Slot
             * @enum {string}
             */
            slot: "top" | "bottom" | "shoes" | "onepiece" | "outerwear" | "accessory";
            /**
             * Audience
             * @default unisex
             * @enum {string}
             */
            audience: "men" | "women" | "unisex";
            /**
             * Primary Color
             * @enum {string}
             */
            primary_color: "black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow";
            /** Secondary Color */
            secondary_color?: ("black" | "white" | "navy" | "gray" | "beige" | "brown" | "blue" | "green" | "red" | "pink" | "purple" | "yellow") | null;
            /**
             * Pattern
             * @default solid
             * @enum {string}
             */
            pattern: "solid" | "striped" | "checked" | "floral" | "graphic";
            /** Warmth */
            warmth: number;
            /** Formality */
            formality: number;
            /** Seasons */
            seasons?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Weather */
            weather?: ("dry" | "rain" | "wind")[];
            /** Tags */
            tags?: string[];
            /**
             * Laundry
             * @default clean
             * @enum {string}
             */
            laundry: "clean" | "dirty" | "unavailable";
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Id */
            id: string;
            /** Archived */
            archived: boolean;
            /** Image Url */
            image_url: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /** GenerateView */
        GenerateView: {
            /** Outfits */
            outfits: components["schemas"]["OutfitView"][];
            /** Candidate Count */
            candidate_count: number;
            /**
             * Approximate
             * @default true
             */
            approximate: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsView */
        InsightsView: {
            /** Vector */
            vector: number[];
            /** Count */
            count: number;
            /** Feature Names */
            feature_names: string[];
            /** Explanation */
            explanation: string;
        };
        /** OutfitView */
        OutfitView: {
            /** Id */
            id: string;
            context: components["schemas"]["Context"];
            /** Garments */
            garments: components["schemas"]["GarmentView"][];
            scores: components["schemas"]["ScoreView"];
            /** Explanations */
            explanations: string[];
            /** Parent Id */
            parent_id: string | null;
        };
        /** Profile */
        Profile: {
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Outfit Style
             * @default all
             * @enum {string}
             */
            outfit_style: "men" | "women" | "all";
            /**
             * Default Occasion
             * @default job interview
             * @enum {string}
             */
            default_occasion: "job interview" | "everyday" | "dinner" | "weekend";
        };
        /** ScoreView */
        ScoreView: {
            /** Color */
            color: number;
            /** Coherence */
            coherence: number;
            /** Comfort */
            comfort: number;
            /** Personal */
            personal: number;
            /** Novelty */
            novelty: number;
            /** Rotation */
            rotation: number;
            /** Total */
            total: number;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Demo */
            demo: boolean;
            profile?: components["schemas"]["Profile"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_auth_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
        };
    };
    save_profile_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_garments_garments_get: {
        parameters: {
            query?: {
                category?: string | null;
                color?: string | null;
                warmth?: number | null;
                formality?: number | null;
                laundry?: string | null;
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarmentView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_garment_garments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GarmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_garment_garments__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attributes"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_garments__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_garments__id__archive_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_images__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_outfits_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Context"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outfit_outfits__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjustment_outfits__id__adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjustmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_outfits__id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackView"][];
                };
            };
        };
    };
    insights_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsView"];
                };
            };
        };
    };
}
